### ISSUE TITLE
ON PEUX PAS LEAVE AVEC CTRL + C !!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by MatisGames35** [MichelBaie/TchouTchou#18]

**Comment by MichelBaie** [comment]
Bonjour et bienvenue sur la hotline TchouTchou (stonkscorp.eu), un agent devrais réparer ce problème d'ici peu. Pour toute autre demande n'hésitez pas à continuer cette discutions avec plus de détails.

**Comment by skyfra** [comment]
Bonjour MathisGames35,

Je suis Kylian (SkyFR#3460) et je vais m'occuper de votre demande.
Il est possible de quitter avec la commande "CTRL C" dans votre terminal et voici la procédure à suivre.
1. Exécutez le script
2. tentez de faire un "CTRL C"
3. spammez le sa mère comme dans l'exemple ci-dessous.

![image](https://user-images.githubusercontent.com/53374108/122804970-cd06d000-d2c8-11eb-87f4-393f93876be3.png)

En cas de besoin n'hésitez pas à nous recontacter

^Kylian, Support Technique et Vice-Président de la stonkscorp

**Comment by MichelBaie** [comment]
Merci beaucoup pour ton aide Kylian.

Je conclue que cette issue est corrigée. Pour plus d'aide, merci d'en rouvrir une.
