### ISSUE TITLE
votre train pollue trop

### ISSUE THREAD

**Issue by louino2478** [MichelBaie/TchouTchou#20]
514 ligne....
faut faire une boucle (pas 300 fois la même ligne)

**Comment by MichelBaie** [comment]
Bonjour,

Notre empreinte carbonne est importante à nos yeux. Je t'invite à réparer le script et à t'ajouter aux contributeurs.
Merci de ta collaboration.

**Comment by louino2478** [comment]
-> #21

**Comment by MichelBaie** [comment]
C'est excellent ! Merci pour votre collaboration.
