### ISSUE TITLE
C'est inadmissible !

### ISSUE THREAD

**Issue by MatthieuLeboeuf** [MichelBaie/TchouTchou#24]
Le programme dit que je n'ai pas installé sl alors que si

**Comment by MichelBaie** [comment]
Support informatique imosoft bonjour,
Creeper à l'appareil.

Afin de mieux vous aider, je vais vous demander de coopérer avec nous.
Pouvez-vous nous communiquer votre OS, Une capture d'écran de votre problème, ainsi qu'une courte explication du problème.

Merci d'avance

**Comment by skyfra** [comment]
Bonjour @MatthieuLeboeuf,

UP ?

**Comment by MichelBaie** [comment]
Bonjour, merci d'avoir fait appel au support imosoft.

Nous n'avons toujours aucune nouvelle de vous.

Je suis obligé de clôre ce ticket.

Au revoir.
