### ISSUE TITLE
Debian 11 | bash: sl: command not found 

### ISSUE THREAD

**Issue by skyfra** [MichelBaie/TchouTchou#25]
Hello, 

Si une personne motivée veut s'occuper de faire la motif relative à debian 11, ou quand on exécute sl.
bash: sl: command not found
le problème vient du fait qu'il ne se trouve pas dans /bin ou /usr/bin mais dans /usr/games.

Je propose en guise de solution (à faire si vous voulez utiliser le script sur debian 11) de créer un lien symbolique avec la commande suivante :  ln -s /usr/games/sl /usr/bin/sl

Ce qui réparera le script ;) 

- Kylian

**Comment by skyfra** [comment]
Merci @Aven678, plus qu'à attendre que @MichelBaie pull ! 👍

**Comment by MichelBaie** [comment]
Bonjour, 

Je viens de constater votre PR.
Je la merge de suite !

Bien à vous,
Tristan
