### ISSUE TITLE
Script non fonctionnel sur Arch linux.

### ISSUE THREAD

**Issue by Endie-157** [MichelBaie/TchouTchou#32]
Bonsoir,
Étant un fan de trains a vapeur, je voulais utiliser ce script sur mon ordinateur pour le décorer avec de belles animations de trains, mais, a mon grand désarroi, il m'affiche une erreur.

`bash: /dev/fd/63: No such file or directory`

Pour information, je suis sur arch linux avec KDE plasma, kernel 6.3.5-arch1-1 (64-bit).
Serait-il possible de réparer ce bug?

**Comment by Endie-157** [comment]
Cher Creeper,

Je vous remercie vivement pour votre réponse diligente à mon problème avec le script TchouTchou. Je suis rassuré de constater que vous prenez cette situation au sérieux et que vous avez déjà pris des mesures pour résoudre le problème.

Je comprends que la résolution des problèmes peut parfois être complexe, et je suis reconnaissant que vous ayez ouvert un ticket de support pour me venir en aide. Je suis impatient de collaborer avec votre équipe de support technique basée au Bangladesh et de trouver une solution à cette erreur frustrante.

Je prends également en compte vos suggestions pour résoudre le problème par moi-même. Je vais m'assurer d'utiliser la dernière version de TchouTchou et de vérifier que toutes les dépendances requises sont correctement installées. De plus, je vais vérifier les autorisations du répertoire et essayer d'exécuter le script en tant qu'utilisateur root ou avec les privilèges d'administrateur. Je consulterai également les discussions et les problèmes signalés par d'autres utilisateurs sur le référentiel GitHub du script TchouTchou pour voir si une solution a déjà été proposée.

Je vous remercie pour votre diligence dans la résolution de ce problème et pour votre compréhension de ma passion pour les trains à vapeur. Je suis convaincu que votre équipe technique trouvera une solution adaptée à ma situation spécifique.

Je resterai à l'écoute et j'attendrai avec impatience le contact de votre équipe de support technique pour avancer dans la résolution de ce problème. Je suis reconnaissant de l'attention que vous portez à mes préoccupations et je suis confiant que, grâce à votre aide, je pourrai profiter pleinement du script TchouTchou et de ses fonctionnalités impressionnantes.

Si j'ai d'autres questions ou préoccupations, je n'hésiterai pas à vous les communiquer. Merci encore pour votre soutien.

Cordialement,

Endie-157

**Comment by MichelBaie** [comment]
Merci bien, cette isue est close jusqu'à réponse du pakistan.
